### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by RaeesBhatti** [k-jackson/jetbrains-hacklang#3]
I'm a heavy user of HackLang and the idea of HackLang support in PhpStorm is just too good to wait to be completed by someone else. Which is why, I would love to contribute to this project, but have almost zero experience working with this kind of packages, although, I do have some basic understanding of how languages are understood at IDE level (tried to build an interpreter from scratch once).

Please point out some guides or documentation that can help the contributors extend this package to add support for more features of the language.

**Comment by k-jackson** [comment]
I'm glad to see the enthusiasm! I started this project knowing almost nothing about compilers (and it shows in some places ;) and nothing about IDE plugins, and lately I've been working on my own toy compiler and programming language to get a better handle on the fundamentals.

### Basic Concepts

An IDE custom language integration is primarily focused on components which are traditionally referred to as a compiler's "front-end": scanning and parsing. Scanning (aka lexing) is the act of transforming text into tokens, and parsing is the act of transforming those tokens and outputting an intermediate program representation (IR). In the case of the Jetbrains IDEs, the IR is known as an abstract syntax tree (AST), and Jetbrains has included classes and utilities for inspecting and working with an AST. Additionally, the scanner is built using a scanner generator (JFlex, which transforms regex down into efficient DFAs), and the parser is built using a parser generator  (Grammar-Kit, which transforms BNF grammar into a recursive descent parser (I think)). The big advantage to using both of these generators is that you can quickly make changes or additions to the scanner or parser, and they also support more advanced operations like custom code or error handling.

### What's Needed to Start _hacking_ (sorry)

This project mostly followed the Jetbrains Custom Language Support tutorial at `http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support_tutorial.html`, and reading through that will likely yield some better insight into the files and structure present. You'll need a copy of IntelliJ (Community Edition is fine), and you'll need to download the IntelliJ source code.

Since this plugin started, Jetbrains updated one or two things regarding custom plugin development and SDK configuration, but I was able to get going with the latest IntelliJ by mixing the docs from the custom language support tutorial and `http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html`. If you're able to get it to the point where you can build the plugin, documenting your steps and adding them to the repo would be a great first addition. If you get stuck getting the SDK running, send me an email and I'll see if I can help.

### Important Project Files
- /resources/META-INF/plugin.xml -- This is like a metadata configuration file for the Jetbrains Plugin itself
- /src/com/hack/hack.flex -- This is the JFlex scanner rule file. Once the project is set up, you can regenerate the scanner by right-clicking the editor and clicking "Run JFlex Generator".
- /src/com/hack/hack.bnf -- This is the GrammarKit grammar file. Once the project is set up, you can regenerate the parser by right-clicking the editor and clicking "Generate Parser Code". Also note that this grammar file was largely created by manually translating the hack-langspec BNF (`https://github.com/hhvm/hack-langspec/blob/master/spec/22-grammar.md`) and working around several spec bugs and issues that arose.

Otherwise, there's lots of other info that you may or may not be interested in learning about at various points in time, but you can always email me (it's in my profile, and I'm on pacific time) for more information or assistance. I'd like to get back into this project, and it's all the better if people actually want it.

**Comment by k-jackson** [comment]
Let me know if there's anything else you're curious about.

**Comment by RaeesBhatti** [comment]
Sure, I will. Thank you 🙇
